---
name: 'Gradle Build (Matrix)'

on:  # yamllint disable-line rule:truthy
  workflow_call: {}     # Reusable workflow

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [11]
        gradle-version: ["wrapper", "7.6.4", "8.6", "current"]
    runs-on: ${{ matrix.os }}
    uses: ./.github/workflows/gradle-build.yaml
    with:
      os: ${{ matrix.os }}
      java-version: ${{ matrix.java-version }}
      gradle-version: ${{ matrix.gradle-version }}
